[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "elastic.elasticcloud"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Elasticsearch", "Elastic Cloud"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-elasticsearch"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
