[package]
org = "yasith_rashan"
name = "deloyment_management"
version = "0.1.0"
distribution = "2201.12.7"

[[dependency]]
org="ballerinax"
name="elastic.elasticcloud"
version="2.0.0"
repository="local"

[build-options]
observabilityIncluded = true
